### ISSUE TITLE
current_task.context['req_id'] = req_id

### ISSUE THREAD

**Issue by GitMastStas** [terrycain/sanic-json-logging#81]
USed your package for one of the projects and this error came up

File /usr/local/lib/python3.6/site-packages/sanic_json_logging/__init__.py, line 48, in log_json_pre

current_task.context['req_id'] = req_id

What can i do to fix it?

TypeError: 'Context' object does not support item assignment while handling path

**Comment by StanislavBerezin** [comment]
Same

**Comment by GitMastStas** [comment]
https://stackoverflow.com/questions/60280109/logging-json-package-for-sanic

**Comment by GitMastStas** [comment]
For the temproarily solution removed section containing
```
    if current_task:
            if hasattr(current_task, 'context'):
                current_task.context['req_id'] = req_id
                current_task.context['req_start'] = start_time
            else:
                current_task.context = {
                    'req_id': str(uuid.uuid4()),
                    'req_start': time.perf_counter()
                }
```

Still does the logs but i guess certain things might be missing, but better than nothing

**Comment by terrycain** [comment]
So task.context is a hack for task local storage, so that a request ID is preserved during the lifecycle of a request, so that any log lines during that request are all tagged with the same request id.

https://github.com/terrycain/sanic-json-logging/blob/master/sanic_json_logging/__init__.py#L27
That changes the default task factory to use [this](https://github.com/terrycain/sanic-json-logging/blob/master/sanic_json_logging/__init__.py#L75) function, which adds a dictionary to the task, and when creating a new task, if there is a task running, it'll copy the dictionary so that the id persists.

Seeing as this code tries to assign a dict to the task object, dict is not a `Context` object so I can only assume something else, possibly sanic itself, is doing something similar to this. I'll have a quick look. Can you put `print(asyncio.get_event_loop().get_task_factory())` above `if current_task:` and see what it prints out to see what the task factory is

**Comment by GitMastStas** [comment]
What i've done for now is just copied the source code of your package and removed that part with "if current_task" completely. It still does the job of displaying sanic root logs in json format.

To answer your question, inside of your file system if i put print(asyncio.get_event_loop().get_task_factory()) it prints "None" if i put in my sanic initialitation it print "here
<function setup_json_logging.<locals>.<lambda> at 0x7f84eb940730>"

**Comment by terrycain** [comment]
I'll update the library to make that part optional. I cant seem to replicate your issue, does it do that with just a base install of sanic and this library? What plugins are you running?

**Comment by GitMastStas** [comment]
I run sanic and sanic jinja2. The error seems to happen when any sort of request is made to sanic from front-end

**Comment by terrycain** [comment]
Can you try v3.0.0 and see if its any better?
